# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - containerTestingACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://sgollapudiimages.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4e053461e6214014935fd6e67640899c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_50f08a151c5f45e281bad6507912c484 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: sgollapudiimages.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4e053461e6214014935fd6e67640899c }}/sg/localnodejs:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'containerTestingACR'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b004360f4b7f41c8bf3f8a920c95439c }}
        images: 'sgollapudiimages.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4e053461e6214014935fd6e67640899c }}/sg/localnodejs:${{ github.sha }}'