name: Build and deploy Node.js app to Azure Web App - nodeJsTesting

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'nodeJsTesting'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        run: |
          npm install --force
          npm run build --if-present
      
  #     - name: Zip artifact for deployment
  #       run: zip release.zip ./* -r
      
  #     - name: Upload artifact for deployment job
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: node-app
  #         path: release.zip

  # deploy:      
  #   runs-on: ubuntu-latest
  #   needs: build
    # environment:
    #   name: 'Production'
    #   url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    # steps:
      - name: Azure login 
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS}}

      - name: App settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          mask-inputs: false
          app-settings-json: '[{ "name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "1", "slotSetting": false }]'
      # - name: Download artifact from build job
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: node-app
      
      # - name: unzip artifact for deployment
      #   run: unzip release.zip
        
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: .
