on: [push]

name: Linux_Container_Node_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}
    
#     - name: Log in to ACR
#       uses: docker/login-action@v2
#       with:
#         registry: https://sgollapudiimages.azurecr.io/
#         username: ${{ secrets.ACR_USERNAME }}
#         password: ${{ secrets.ACR_PASSWORD }}
        
    # - name: Build and push container image to ACR
    #   uses: docker/build-push-action@v3
    #   with:
    #     context: .
    #     push: true
    #     tags: sgollapudiimages.azurecr.io/sg/localnodejs:latest
    #     file: ./Dockerfile     
    
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'singleContainerTesting'
        slot-name: 'production'
        images: sgollapudiimages.azurecr.io/sg/localnodejs:latest
    
    - name: Azure logout
      run: |
        az logout
