on: [push]

name: SingleContainerTesting

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}
    
    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}


#     - name: Log in to ACR
#       uses: azure/docker-login@v1
#       with:
#         registry: https://sgollapudiimages.azurecr.io/
#         username: ${{ secrets.ACR_USERNAME }}
#         password: ${{ secrets.ACR_PASSWORD }}
        
#     - name: Build and push container image to registry
#       uses: docker/build-push-action@v3
#       with:
#         push: true
#         tags: index.docker.io/${{ secrets.REGISTRY_USERNAME }}/nodejshelloworld:latest
#         file: ./Dockerfile     
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'singleContainerTesting'
        slot-name: 'clone'
        images: index.docker.io/${{ secrets.REGISTRY_USERNAME }}/nodejshelloworld:latest
#         images: sgollapudiimages.azurecr.io/sgollapudiimages/sg/localnodejs:latest
    
    - name: Azure logout
      run: |
        az logout
